import «LeanTutorialBenchmark».«TheMechanicsOfProof».ProofByCalculation
import «LeanTutorialBenchmark».«TheMechanicsOfProof».ProofWithStructure
import «LeanTutorialBenchmark».«TheMechanicsOfProof».ParityAndDivisibility
import «LeanTutorialBenchmark».«TheMechanicsOfProof».ProofWithStructureII
import «LeanTutorialBenchmark».«TheMechanicsOfProof».Logic
import «LeanTutorialBenchmark».«TheMechanicsOfProof».Induction
import «LeanTutorialBenchmark».«TheMechanicsOfProof».NumberTheory
import «LeanTutorialBenchmark».«TheMechanicsOfProof».Functions
import «LeanTutorialBenchmark».«TheMechanicsOfProof».Sets
import «LeanTutorialBenchmark».«TheMechanicsOfProof».Relations
